### ISSUE TITLE
Plugin is not seeing/formatting files during manual run.

### ISSUE THREAD

**Issue by mcpierce** [Cosium/git-code-format-maven-plugin#137]
**What steps will reproduce the problem?**
1. Add the plugin to our root pom.xml
1. Run the following command line: ```mvn git-code-format:format-code -Dgcf.globPattern=**/*.java```

**What is the expected output?**
1. The source code for the project should be reformatted using Google's code convention for Java.

**What happens instead?**
1. The plugin finishes saying success, but none of our project's code is reformatted.

**Environment:**
 - OS: MacOS Ventura 13.4.1
 - Git version: 2.39.2
 - git-code-format-maven-plugin version: 2.4
 - Maven version: 3.5.3

**Link to a git repository that can be cloned to reproduce the problem:**
I can't share this as it's a private repo for work.

**Additional context**

**Comment by reda-alaoui** [comment]
Closing, because, given the provided information, only you will be able to fix the issue.
But you can still try to upgrade to the latest version of the plugin.

**Comment by mcpierce** [comment]
@reda-alaoui So, not even going to provide advice on where to look or what to check?
