### ISSUE TITLE
ghost unstaged files after commit

### ISSUE THREAD

**Issue by wli-git** [Cosium/git-code-format-maven-plugin#43]
After git commit with pre-commit hook, command "git status" shows formatted files as unstaged files, even though there is no real diff in the files.

```
$ git version
git version 2.23.0.windows.1
```

**Comment by delebota** [comment]
Same here, using the 2.0 release.

**Comment by delebota** [comment]
Can't edit my comment for some reason, but I assume it's a newline issue?

**Comment by reda-alaoui** [comment]
A test case must be provided.

**Comment by reda-alaoui** [comment]
I think it is fixed by https://github.com/Cosium/git-code-format-maven-plugin/issues/42.
If it is not, please reopen this issue.
