### ISSUE TITLE
can svn use？

### ISSUE THREAD

**Issue by drduan** [Cosium/git-code-format-maven-plugin#50]
[ERROR] Failed to execute goal com.cosium.code:git-code-format-maven-plugin:2.4:format-code (default-cli) on project master-data-system: Execution default-cli of g
oal com.cosium.code:git-code-format-maven-plugin:2.4:format-code failed: One of setGitDir or setWorkTree must be called. -> [Help 1]

**Comment by reda-alaoui** [comment]
Only git

**Comment by reda-alaoui** [comment]
The plugin needs to write git hook files to intercept git operations.
Those files are written on maven goal execution.
So no.
