### ISSUE TITLE
On Windows .cmd extension cause ''C:\Program' is not recognized as an internal or external command, operable program or batch file.'

### ISSUE THREAD

**Issue by yl-coder** [Cosium/git-code-format-maven-plugin#53]
**What steps will reproduce the problem?**
1. mvn git-code-format:install-hooks
2. Change some code
3. run git commit -m "exclude for now"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**What is the expected output?**
Githook should be triggered and code should be formatted
**What happens instead?**
Terminal output 
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Environment:**
 - OS: Windows 10
 - Git version: git version 2.27.0.windows.1
 - git-code-format-maven-plugin version: 2.5

**Link to a git repository that can be cloned to reproduce the problem:**
This is happens on my machine only. The reason is because in ~\IdeaProjects\{project_name}\.git\hooks\{project_name}.git-code-format.pre-commit content has a .cmd postfix which cause the prehook command to fail.

**Additional context**
I solved this by removing .cmd postfix in {project_name}.git-code-format.pre-commit file

Before
#!/bin/bash
set -e
"C:/Program Files/JetBrains/IntelliJ IDEA 2019.1.4/plugins/maven/lib/maven3/bin/mvn.cmd" -f "C:/Users/{home}/IdeaProjects/{project_name}/pom.xml" com.cosium.code:git-code-format-maven-plugin:on-pre-commit 

After

#!/bin/bash
set -e
"C:/Program Files/JetBrains/IntelliJ IDEA 2019.1.4/plugins/maven/lib/maven3/bin/mvn" -f "C:/Users/{home}/IdeaProjects/{project_name}/pom.xml" com.cosium.code:git-code-format-maven-plugin:on-pre-commit

**Comment by yl-coder** [comment]
The problem still persists in 2.6, 

Realised it uses my maven_home maven now.

but the extension .cmd in git-code-format.pre-commit still causing the same issue. 

I'm using Apache Maven 3.6.3

**Comment by reda-alaoui** [comment]
Can you please remove the precommit hook and retry? If it does not work, can you please provide the content of the precommit hook?

**Comment by reda-alaoui** [comment]
Please reopen when ready.

**Comment by yl-coder** [comment]
@reda-alaoui  Sorry for late response.

I'm using the latest com.cosium.code 2.6

This is the content. I can fix it manually by removing .cmd

#!/bin/bash
set -e
"C:/Program Files/apache-maven-3.6.3/bin/../bin/mvn.cmd" -f "C:/Users/You Liang/IdeaProjects/sampleproject/pom.xml" com.cosium.code:git-code-format-maven-plugin:on-pre-commit

**Comment by reda-alaoui** [comment]
Please list the content of `C:/Program Files/apache-maven-3.6.3/bin`

**Comment by yl-coder** [comment]
The reason is my pom file has white spaces on it, due to my username. After moving my project to a path with no white spaces, the error no longer appears. 

C:/Users/You Liang/IdeaProjects/sampleproject/pom.xml

>> shift the sampleproject to a path with no white space works for my case.
