### ISSUE TITLE
Unable to choose Google style option for empty blocks

### ISSUE THREAD

**Issue by javydreamercsw** [Cosium/git-code-format-maven-plugin#54]
**What steps will reproduce the problem?**
1. Have code like:
`  void doNothing() {}`
2. Plugin formats to:
```
  void doNothingElse() {
  }
```
As per [Google-style ]( https://google.github.io/styleguide/javaguide.html#s4.1.3-braces-empty-blocks)both are acceptable but plugin enforces one. Some teams might like to enforce one vs. the other.

**What is the expected output?**
Configured one.
**What happens instead?**
Multiline is enforced.
**Environment:**
 - OS: Mac Catalina 10.15.6
 - Git version: 2.24.3
 - git-code-format-maven-plugin version: 2.4
 - Maven version: 3.5.4

**Comment by reda-alaoui** [comment]
The plugin directly uses https://github.com/google/google-java-format.
This issue should be addressed to https://github.com/google/google-java-format.
