### ISSUE TITLE
unable to commit the class formatted if there is any unformatted before

### ISSUE THREAD

**Issue by northerndeveloper** [Cosium/git-code-format-maven-plugin#57]
Hello

When I execute cosium git-code-format-maven-plugin, it says there is one class which needs to be formatted.I format myself but I still come across with that error, afterwards I remove validation goal from the plugin as it was suggested before but when I commit a class it does not commit it ! I think clean install with goal validation needs to be accomplished in order to run pre-commit hook and commit the code formatted ?

What is your suggestion?

Thank you for your helps

**Comment by reda-alaoui** [comment]
Hello,

> I format myself but I still come across with that error

You probably don't format it with Google Java Format. Use the manual code formatting provided by this plugin instead:
https://github.com/Cosium/git-code-format-maven-plugin#manual-code-formatting

**Comment by reda-alaoui** [comment]
Any goal will deploy the precommit hook.
`mvn initialize` will do for example.

**Comment by reda-alaoui** [comment]
Please stop using the blank template and use the bug template to create issues.

**Comment by reda-alaoui** [comment]
No feedback for months. Closing.
