### ISSUE TITLE
com.google.googlejavaformat.java.FormatterException: error: Imports not contiguous (perhaps a comment separates them?)

### ISSUE THREAD

**Issue by varununnikrishnan** [Cosium/git-code-format-maven-plugin#65]
default-cli of goa l com.cosium.code:git-code-format-maven-plugin:2.4:format-code failed: com.google.googlejavaformat.java.FormatterException: error: Imports not contiguous (perhaps a comment separates them?)

**Comment by reda-alaoui** [comment]
Unactionable.
