### ISSUE TITLE
Java 16+ support

### ISSUE THREAD

**Issue by hashworks** [Cosium/git-code-format-maven-plugin#73]
**What steps will reproduce the problem?**
1. Use openjdk 16
2. Run `mvn git-code-format:format-code`
3. Watch it fail

**What is the expected output?**
Success

**What happens instead?**
```
[INFO] --- git-code-format-maven-plugin:3.0:format-code (default-cli) @ projectname ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.394 s
[INFO] Finished at: 2021-07-02T13:19:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.cosium.code:git-code-format-maven-plugin:3.0:format-code (default-cli) on project projectname: Execution default-cli of goal com.cosium.code:git-code-format-maven-plugin:3.0:format-code failed: An API incompatibility was encountered while executing com.cosium.code:git-code-format-maven-plugin:3.0:format-code: java.lang.IllegalAccessError: class com.google.googlejavaformat.java.JavaInput (in unnamed module @0x73d3e555) cannot access class com.sun.tools.javac.parser.Tokens$TokenKind (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.parser to unnamed module @0x73d3e555
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.cosium.code:git-code-format-maven-plugin:3.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
```

**Environment:**
 - OS: Arch Linux
 - Git version: 2.32.0
 - git-code-format-maven-plugin version: 3.0
 - Maven version: 3.8.1
 - Java version: 16.0.1

**Additional context**
https://github.com/google/google-java-format/issues/538
https://github.com/google/google-java-format/issues/612

**Comment by mudlee** [comment]
It still doesn't work if I use `3.1`. Is that possible that it's not been released?

**Comment by reda-alaoui** [comment]
@mudlee I can confirm that the fix is in 3.1.
You can see the tag at https://github.com/Cosium/git-code-format-maven-plugin/commit/62a8da70ffa5470584694bb1b739a3f323236119

**Comment by reda-alaoui** [comment]
@hashworks does it work for you on 3.1?

**Comment by mudlee** [comment]
See the images below. I've already removed `~/.m2` and cleaned my env, no luck.

![1](https://user-images.githubusercontent.com/1439334/124558021-7659d400-de3a-11eb-9954-a9b0d1a48f79.png)
![2](https://user-images.githubusercontent.com/1439334/124558025-78239780-de3a-11eb-809e-b9e31e07f9ae.png)
![3](https://user-images.githubusercontent.com/1439334/124558038-7a85f180-de3a-11eb-8cdb-5f558b6a82d5.png)

**Comment by reda-alaoui** [comment]
According to https://github.com/google/google-java-format/releases/tag/v1.10.0, java flags must be passed in addition.

**Comment by mudlee** [comment]
> According to https://github.com/google/google-java-format/releases/tag/v1.10.0, java flags must be passed in addition.

Thanks for the blazing fast help! May I ask how can I add these flags in a case of maven? I've tried  everything I know, but I cannot pass java args to the plugin :(

**Comment by mudlee** [comment]
OK, prepending the `mvnw` cli with these below works!
```
MAVEN_OPTS="--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED"
```

**Comment by hashworks** [comment]
Is there a way to add those to the `pom.xml` or integrate them into the plugin?

**Comment by reda-alaoui** [comment]
The plugin can format/verify code at 2 occasions:
- after a manual trigger
- after a commit

To my knowledge, the only way to pass java options for the first case would be to fork a new VM (the same way maven surefire plugin can do). That looks really overkill.

Meanwhile, I think using https://maven.apache.org/configure.html#mvn-jvm-config-file should solve your issue.

**Comment by reda-alaoui** [comment]
I added https://github.com/Cosium/git-code-format-maven-plugin/blob/master/README.md#jdk-16-peculiarities to the README.
