### ISSUE TITLE
Add maxLineLength option

### ISSUE THREAD

**Issue by jimbethancourt** [Cosium/git-code-format-maven-plugin#76]
I noticed https://github.com/talios/googleformatter-maven-plugin has a maxLineLength option. It would be great to have that option available for this plugin as well.  I prefer a line length of 120 and being able to set that would really helpful.

Thanks,
Jim

**Comment by reda-alaoui** [comment]
This so called option allowed to change the line length limit of the Javadoc, not the code.
The referred maven plugin uses a Mockito hack to modify its value. See https://github.com/talios/googleformatter-maven-plugin/blob/2034133fe14f0ee928c6942cd037f1fbd52f0abd/src/main/java/com/theoryinpractise/googleformatter/GoogleFormatterMojo.java#L142.
So it was never an option.

There is no trace of this construct in Google Java Format 1.13 .
