### ISSUE TITLE
Update google java format to 1.15.0

### ISSUE THREAD

**Issue by valeriuvancea** [Cosium/git-code-format-maven-plugin#86]
It would be nice to update the google java format version to 1.15.0, so there will be no need for the --add-exports

**Comment by duke1995** [comment]
FYI: According to this comment on the google-java-format GitHub site, the `--add-exports` flags are no longer needed when invoking the CLI using `java -jar`, but they are still needed when using google-java-format as a library (which is the case for this plugin): [Java 17 compatibility · Issue #612 · google/google-java-format](https://github.com/google/google-java-format/issues/612#issuecomment-1108685891)

I don't use Java 17, so I haven't been able to verify this issue myself.

**Comment by reda-alaoui** [comment]
Thanks for letting me now. The documentation change has to be reverted in this case.

**Comment by duke1995** [comment]
@reda-alaoui 

I did a test to be sure and documented the results [here](https://github.com/Cosium/git-code-format-maven-plugin/commit/85fca3e6b2eb63a19e3bcabbfb85ea573a02e600#commitcomment-74628699). In summary, it will be best to revert the documentation change for the time being, as you suggested above.

**Comment by reda-alaoui** [comment]
Fixed in https://github.com/Cosium/git-code-format-maven-plugin/commit/ca389ebf6d7f84915055164af51cabb33daa7eb9
