### ISSUE TITLE
A string instead of a command is added into my pre-commit file.

### ISSUE THREAD

**Issue by tiansu-yu-idealo** [Cosium/git-code-format-maven-plugin#89]
I have added the configurations in `pom.xml` like instructed in README, and every command works quite well. The only exception is that `mvn git-code-format:format-code` is not triggered like a pre-commit hook should. 

Upon debugging, I realized this maven plugin adds this line of string into my `.git/hooks/pre-commit`:
```
"$(git rev-parse --git-dir)/hooks/user-profile-flink-java-app.git-code-format.pre-commit.sh"
```
which is just a string, instead of a real command inside pre-commit file:
```
$(git rev-parse --git-dir)/hooks/user-profile-flink-java-app.git-code-format.pre-commit.sh
```
After remove the `"` wrapping, everything works as normal. Of course, a new mvn call will trigger this plugin to add the old string back, but that is harmless. 

I want to ask if this is intended or ?

**Comment by reda-alaoui** [comment]
Hello, use the bug report template.
