### ISSUE TITLE
Java 17 not support

### ISSUE THREAD

**Issue by sheiy** [Cosium/git-code-format-maven-plugin#92]
class com.google.googlejavaformat.java.JavaInput (in unnamed module @0x5f9b6ae7) cannot access class com.sun.tools.javac.parser.Tokens$TokenKind (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.parser to unnamed module @0x5f9b6ae7

**Comment by reda-alaoui** [comment]
https://github.com/Cosium/git-code-format-maven-plugin#jdk-16-peculiarities
