### ISSUE TITLE
IntelliJ shows already commited files in changelist

### ISSUE THREAD

**Issue by FireRedDev** [Cosium/git-code-format-maven-plugin#93]
**What steps will reproduce the problem?**
1. Commit in IntelliJ
**What is the expected output?**
No Changes afterwards
**What happens instead?**
Intellij shows previously commited files as to be commited in the next commit, but they are the same content/equal/no changes
**Environment:**
 - OS: [e.g. Windows 10]

**Additional context**
I have found that a workaround is to execute in a postcommit hook "git update-index -g". Can you add this?

**Comment by reda-alaoui** [comment]
Please follow the bug issue template.
